import './global.css';
import { UiHeader } from '@demo-form-renderer/ui-design-system';

export const metadata = {
  title: 'Welcome to oa-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UiHeader />
        {children}
      </body>
    </html>
  );
}
